name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Se ejecuta en cada push a la rama main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Ajusta la versión según tu proyecto

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to main branch
        run: |
          # Crea la carpeta docs si quieres usarla como subdirectorio
          mkdir -p docs
          # Copia el contenido de dist a docs (o usa dist directo)
          cp -a dist/. docs/ 

      - name: Commit and push changes
        run: |
          git config --global user.name "Jesús Antonio Zúñiga Arce"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs  # Si usas /docs como subdirectorio; cambia a "." si es la raíz
          git commit -m "Deploy to GitHub Pages"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

